### ISSUE TITLE
Add privilege separation

### ISSUE THREAD

**Issue by sid77** [nsheridan/cashier#25]
Right now the only way to bind to privileged ports is to start the program as `root`. Ideally we should:

1. start as root
2. read TLS certificate & key, if needed
3. bind to privileged port
4. drop privileges to some other user (`www` or `www-data` or whatever)
5. ...
6. profit!

**Comment by nsheridan** [comment]
Related: https://github.com/golang/go/issues/1435

**Comment by nsheridan** [comment]
Also related
