### ISSUE TITLE
Datastore config is too complicated

### ISSUE THREAD

**Issue by nsheridan** [nsheridan/cashier#32]
Using a colon-delimited string for datastore configuration is complicated and annoying.
It should be converted to a key-value series. Examples:

``` hcl
server {
  datastore {
    type = "mysql"
    username = "user"
    password = "passwd"
    address = "my-db-host.corp:3306"
  }
}

server {
  datastore {
    type = "mongo"
    username = "user"
    password = "passwd"
    address = "my-mongo-host1.corp,my-mongo-host2.corp"
  }
}

server {
  datastore {
    type = "sqlite"
    filename = "/data/cashier.db"
  }
}
```

This has the benefit of making it easier to use vault for datastore passwords.
This will break existing configs so some form of detection and warning or compatibility should be employed.

**Comment by nsheridan** [comment]
This is pretty much done with a `server.database` option.
TODO: remove support for the `server.datastore` option.

**Comment by lyda** [comment]
This is done now as well.
