### ISSUE TITLE
Improve client.GenerateKey API when generating Ed25519 keys

### ISSUE THREAD

**Issue by patrickod** [nsheridan/cashier#33]
Right now we need to pass the bit length parameter which isn't going to be used.

**Comment by nsheridan** [comment]
Yeah, this is gross.

There's a couple ways to make this better - the obvious way is to use an options struct:
https://github.com/nsheridan/cashier/pull/38

This is another possibility which I tried out after reading some interesting posts by [Rob Pike](https://commandcenter.blogspot.ie/2014/01/self-referential-functions-and-design.html) and [Dave Cheney](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis):
https://github.com/nsheridan/cashier/pull/39

I think both PRs improve things, but I think the latter is better. I'm interested in your feedback.
