### ISSUE TITLE
Support critical options in certs

### ISSUE THREAD

**Issue by nsheridan** [nsheridan/cashier#42]
SSH certificates support both `extensions` and `critical options`. The former holds options such as `permit-pty, permit-agent-forwarding, permit-X11-forwarding` while critical options allows for options like `source-address` and `force-command`.
Cashier supports extensions via the `permissions` option. It should also support critical options.

**Comment by patrickod** [comment]
IP restriction to the client IP would be an interesting default. Makes certificates even less useful to anyone that gets their hands on one.

**Comment by nsheridan** [comment]
Hard to make a default without making some serious assumptions about the client. Like: Can you assume an IPv4 or IPv6 network? Will it be annoying if they connect to local machines on a LAN as well as remote machines behind a NAT? Will they have to re-cert every time their laptop hops network (I'm being selfish with this one - between work, home and hotspot my source ip probably changes about 4 times a day)?

Given that cashier stashes keys and certificates in the ssh agent and the private key doesn't leave the client I'm not sure that there's much risk here.

**Comment by patrickod** [comment]
I think I should have stated s/default/feature :)

**Comment by nsheridan** [comment]
:)

**Comment by nsheridan** [comment]
Branch in progress: https://github.com/nsheridan/cashier/compare/critical_options
Needs some tests and some doc. Should get merged before the weekend.

**Comment by nsheridan** [comment]
Some testing:

```
config:
ssh {
  signing_key = "ca"
  max_age = "5m"
  permissions = ["permit-pty", "force-command=/usr/bin/fortune bofh-excuses"]
}

cert:
% ssh-add -L |grep cert-v01 | ssh-keygen -f - -L
(stdin):1:
        Type: ssh-ed25519-cert-v01@openssh.com user certificate
        Public key: ED25519-CERT SHA256:0wFr1vk+mGfOksIya0Qj2JUSb1s75lGPjZFuU2jD32I
        Signing CA: ED25519 SHA256:zighrTH2X+oB1ekqQqkJdCv1W/AsizPsG0b3j0mS9HA
        Key ID: "nsheridan_1484180068"
        Serial: 0
        Valid: from 2017-01-12T00:09:28 to 2017-01-12T00:19:28
        Principals:
                nsheridan
        Critical Options:
                force-command /usr/bin/fortune bofh-excuses
        Extensions:
                permit-pty

% ssh banana
runaway cat on system.
Connection to banana closed.
```

**Comment by nsheridan** [comment]
merged
