### ISSUE TITLE
Dropping privileges might not work as expected

### ISSUE THREAD

**Issue by TheTincho** [nsheridan/cashier#64]
Hi,

Maybe this was already considered and determined not to be an issue, but I am worried by the use of [drop.DropPrivileges](https://github.com/nsheridan/cashier/blob/master/server/server.go#L82) in the code, as this might result in some threads retaining their privileges due to the limitations of the golang runtime.

There is a discussion about this in the go issue tracker: https://github.com/golang/go/issues/1435

**Comment by nsheridan** [comment]
You're totally right, and might give a false sense of security. I'll document this.

**Comment by sid77** [comment]
Also, more background info on privilege separation in cashier (and Go):
- the issue that started everything, short read, already with warnings https://github.com/nsheridan/cashier/issues/25
- the PR that introduced it, longer read, lots of comments https://github.com/nsheridan/cashier/pull/27

**Comment by nsheridan** [comment]
I've updated the appropriate section of the [README](https://github.com/nsheridan/cashier#server-1)
