### ISSUE TITLE
Evaluate non-organisation configuration options for github / google providers

### ISSUE THREAD

**Issue by patrickod** [nsheridan/cashier#8]
In the case where one wants to use either the `github` or `google` authentication providers without an organisation of individuals it'd be nice to have a whitelist of either `@gmail.com` usernames or github usernames to which one could extend access via cashier.

Thinking it'd look like 
```
  "provider_opts": {
    "usernames": ["patrickod", "nsheridan"]
  } 
```
for both, as usernames work for both @gmail.com or github. Not-so-minor edge-case for GApps folks who don't have @gmail.com addresses but to whom you'd like to extend access. Maybe for google it's an `emails` field instead?

**Comment by nsheridan** [comment]
Google oauth doesn't provide usernames, just emails: https://github.com/nsheridan/cashier/blob/master/server/auth/google/google.go#L114

**Comment by nsheridan** [comment]
https://github.com/bitly/oauth2_proxy/blob/42f1651ba5ab411e3216bd46f3c90bab153a2f13/validator.go#L39-60

**Comment by sid77** [comment]
I'm currently working on this ☝️

**Comment by sid77** [comment]
See https://github.com/nsheridan/cashier/pull/21

**Comment by sid77** [comment]
#21 is in, closing
