### ISSUE TITLE
Certificate Signed By unknown authority

### ISSUE THREAD

**Issue by shubhampatel-vphrase** [nsheridan/cashier#82]
After the google auth I am getting the following error

    Error on /auth/callback: Post https://accounts.google.com/o/oauth2/token: x509: certificate signed by unknown authority

I have generated signing_key using ```ssh-keygen -f ssh_ca```.
Am I missing any step?
Thank You.

**Comment by mister2d** [comment]
The CA chain included in cashier is busted. It needs fixing and not be a self signed CA `pem`.

**Comment by nsheridan** [comment]
Apologies for the delay in fixing this - real life got in the way. I've updated the base container image from `scratch` to `gcr.io/distroless/scratch` which is less minimal, but includes the root certs.

@mister2d The base alpine image wouldn't fix anything here - it doesn't include ca-certificates.
